apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: free-mlops-ingress
  namespace: free-mlops
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - free-mlops.local
    secretName: free-mlops-tls
  rules:
  - host: free-mlops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: free-mlops-app-service
            port:
              number: 8501
      - path: /mlflow
        pathType: Prefix
        backend:
          service:
            name: free-mlops-mlflow-service
            port:
              number: 5000
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: free-mlops-api-service
            port:
              number: 8000
